# satnogs-monitor example config

# log level 0 -> WARN, 1 -> INFO, 2 -> DEBUG, 3 -> TRACE
log_level = 1


[[stations]]
# Your stations SatNOGS id
satnogs_id = 175
# The local IP address of your station
# This will be used to get realtime information like system status, CPU temperature, ...
# NOT USED YET
# rt_ip = "192.168.0.13"
# The port of the station node providing realtime information
# NOT USED YET
# rt_port = 8377

[ui]
# number of orbits plotted on the map
ground_track_num = 3
