[package]
name = "gs-net"
version = "0.1.0"
authors = ["Sebastian Woetzel <wose@zuendmasse.de>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
log = "0.4.5"
rmp-rpc = "0.3.0"
tokio = "0.1.11"

[dev-dependencies]
pretty_env_logger = "0.2.4"